### ISSUE TITLE
Calculate and display Words Per Minute (WPM)

### ISSUE THREAD

**Issue by AJGreaves** [AJGreaves/typeracer-lesson-plan-repo#5]
**User story**

As a user, I want to see my typing speed calculated in Words Per Minute (WPM) when I finish typing so that I know my typing performance.

**Acceptance Criteria:**

- [ ] WPM is calculated based on the number of typed words and elapsed time.
- [ ] The WPM result is displayed immediately after completing the test.

**Tasks:**

- [x] Create a results area to display the level, time and Words Per Minute (WPM) results to the user
- [ ] Implement functionality to calculate the number typed WPM.
- [ ] Display the WPM result immediately after the user completes the test.
