### ISSUE TITLE
Test instructions modal

### ISSUE THREAD

**Issue by AJGreaves** [AJGreaves/typeracer-lesson-plan-repo#8]
**User story**

As a new user, I want clear instructions on how to use the typing speed test so that I know how to start and complete the test.

**Acceptance Criteria:**

- [ ] Clear instructions on how to take the test are provided on the homepage.
- [ ] Instructions are easy to understand and follow.

**Tasks:**

- [ ] Create a modal that displays clear instructions to the user on how to take the test.
- [x] Add a clearly visible button on the web page to open the instructions modal.
